server:
  port: 8080

spring:
  #热部署生效
  #设置重启的目录，添加那个目录的文件需要restart
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java



  #设定静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**



  # thymeleaf 静态资源配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #关闭缓存，即时刷新，上线生产环境需要改为true
    cache: false


